Add .github, examples and docker to .gitattributes
jakubkulhan/bunny pull request #140
Opened 2023-07-29 15:39 UTC by VincentLanglet

Hi @WyriHaximus 

I saw a gitattribute were added but I think some entries are missing
- Examples are not mandatory when downloading the libraries
- The docker folder is for local development if I understand correctly
- the .github folder is not needed

2023-07-31 20:02 UTC, WyriHaximus requested changes
Sounds like a solid plan. IMHO the only things exported should be `composer.json`, the `src` folder, and the license file. So this change set would bring us almost there. Can you make these two changes?:
* Also ignore the `tutorials` directory
* Sort everything alphabetically, makes it easier to check what is ignore and what isn't

2023-07-31 20:03 UTC, VincentLanglet commented
There is already the tutorial folder
https://github.com/jakubkulhan/bunny/pull/140/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR4

2023-07-31 20:38 UTC, VincentLanglet commented
I sorted the entries @WyriHaximus :)

2023-07-31 21:17 UTC, WyriHaximus commented
> There is already the tutorial folder https://github.com/jakubkulhan/bunny/pull/140/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR4

Hah you're right, this is why the sorting is handy :sweat_smile:

2023-07-31 21:31 UTC, WyriHaximus approved these changes
Thank you for putting the time and effort into this :+1:

2023-07-31 21:31 UTC, merged

2023-08-03 13:18 UTC, VincentLanglet commented
You're welcome ; do you ming releasing https://github.com/jakubkulhan/bunny/compare/v0.5.4...master or do you plan to do more merge ?

2023-08-06 22:07 UTC, WyriHaximus commented
@VincentLanglet Will do so tomorrow morning, prepped everything just now. There are plans to merge more but it makes sense to get this out now over waiting for all the 0.6 changes to get in. Will also make sure to have a 0.5 and a 0.6 branch for the long term branching.

2023-08-07 07:04 UTC, WyriHaximus commented
@VincentLanglet [`v0.5.5`](https://github.com/jakubkulhan/bunny/releases/tag/v0.5.5) has been tagged